
# Default values for k8s-practice-dev.
# Override postgres credentials!!!
postgres:
  adminPassword: ExampleAdminPassword
  userPassword: ExampleUserPassword
  replicationPassword: ExampleReplicationPassword


# Override postgres password configuration.
postgresql:
  auth:
    database: test-database
    # Name for a custom user to create
    username: postgres-user
    # Set secret name that contain secretKeys
    existingSecret: postgres-secret
    # Just in case overriding secretKeys names to match template secret
    secretKeys:
      adminPasswordKey: postgres-password
      userPasswordKey: password
      replicationPasswordKey: replication-password
  backup:
    enabled: true
    cronjob:
      storage:
        size: 25Gi

# Set the service type to NodePort to be accessible for administration
  primary:
    persistence:
      enabled: true
      size: 24Gi
    service:
      type: NodePort
      nodePorts:
        postgresql: 30504

  architecture: replication

  readReplicas:
    persistence:
      enabled: true
      size: 24Gi
    service:
      type: NodePort
      nodePorts:
        postgresql: 30505


# Setup for portainer
portainer:
  image:
    tag: 2.21.4
  service:
    type: NodePort
    httpNodePort: 30777