apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ .Release.Name }}-ingress
  labels:
    app: {{ .Release.Name }}-fastapi
  {{- with .Values.ingress.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  {{- if .Values.ingress.className }}
  ingressClassName: {{ .Values.ingress.className }}
  {{- end }}
  rules:
    - host: {{ .Values.ingress.host }}
      http:
        paths:
          - path: {{ .Values.ingress.api_path }}
            pathType: {{ .Values.ingress.pathType }}
            backend:
              service:
                name: {{ .Release.Name }}-fastapi
                port:
                  number: {{ .Values.fastapi.port }}

  {{- if .Values.ingress.tls }}
  tls:
    - hosts:
      - {{ .Values.ingress.host }}
      secretName: {{ .Values.ingress.tlsSecretName }}
  {{- end }}


{{/*apiVersion: networking.k8s.io/v1*/}}
{{/*kind: Ingress*/}}
{{/*metadata:*/}}
{{/*  name: minimal-ingress*/}}
{{/*spec:*/}}
{{/*  ingressClassName: nginx*/}}
{{/*  rules:*/}}
{{/*    - host: k8s-practice.local*/}}
{{/*      http:*/}}
{{/*        paths:*/}}
{{/*        - path: /*/}}
{{/*          pathType: Prefix*/}}
{{/*          backend:*/}}
{{/*            service:*/}}
{{/*              name: {{ .Release.Name }}-fastapi*/}}
{{/*              port:*/}}
{{/*                number: 8000*/}}
