apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: {{ .Release.Name }}-redis
  labels:
    app: {{ .Release.Name }}-redis
spec:
  serviceName: {{ .Release.Name }}-redis
  replicas: {{ .Values.fastapi.replicas }}
  selector:
    matchLabels:
      app: {{ .Release.Name }}-redis
  template:
    metadata:
      labels:
        app: {{ .Release.Name }}-redis
    spec:
      containers:
      - name: redis
        image: {{ .Values.redis.image }}
        ports:
        - containerPort: {{ .Values.redis.port }}
        command: ["redis-server"]
        args: {{ .Values.redis.run_args }}
        {{- if and .Values.redis.persistence.enabled (ne .Values.redis.persistence.storageClass "") }}
        volumeMounts:
          - name: redis-data
            mountPath: /data
        {{- end }}
  {{- if and .Values.redis.persistence.enabled (ne .Values.redis.persistence.storageClass "") }}
  volumeClaimTemplates:
  - metadata:
      name: {{ .Values.redis.persistence.name }}
    spec:
      accessModes: [ "ReadWriteOnce" ]
      storageClassName: {{ .Values.redis.persistence.storageClass }}
      resources:
        requests:
          storage: {{ .Values.redis.persistence.size }}
  {{- end }}
