apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-redis
  labels:
    app: {{ .Release.Name }}-redis
spec:
  clusterIP: None
  selector:
    app: {{ .Release.Name }}-redis
  ports:
    - port: {{ .Values.redis.port }}
      name: redis
