# This file contains secrets setup with default values. This values should be overridden in values.yaml or set in the command line.

apiVersion: v1
kind: Secret
metadata:
  name: postgres-secret
data:
    postgres-password: {{ .Values.postgres.adminPassword | b64enc }}
    password: {{ .Values.postgres.userPassword | b64enc }}
    replication-password: {{ .Values.postgres.replicationPassword | b64enc }}
