# This file contains secrets setup with default values. This values should be overridden in values.yaml or set in the command line.

apiVersion: v1
kind: Secret
metadata:
  name: postgres-secret
data:
    postgres-password: {{ .Values.credentials.postgres.adminPassword | b64enc }}
    password: {{ .Values.credentials.postgres.userPassword | b64enc }}
    replication-password: {{ .Values.credentials.postgres.replicationPassword | b64enc }}


---

apiVersion: v1
kind: Secret
metadata:
  name: grafana-secret
  namespace: monitoring
data:
    admin-user: {{ .Values.credentials.grafana.adminUser | b64enc }}
    admin-password: {{ .Values.credentials.grafana.adminPassword | b64enc }}



{{- range $index, $ing := .Values.ingresses }}
{{- if and $ing.tls.enabled $ing.tls.dev.createSecret $ing.tls.dev.certFile $ing.tls.dev.keyFile }}

{{- if eq $.Values.deploymentType "dev" }}
---
apiVersion: v1
kind: Secret
metadata:
  name: {{ $ing.tls.dev.secretName }}
  namespace: {{ $ing.namespace | default $.Release.Namespace }}
type: kubernetes.io/tls
data:
  tls.crt: {{ $.Files.Get $ing.tls.dev.certFile | b64enc }}
  tls.key: {{ $.Files.Get $ing.tls.dev.keyFile | b64enc }}
{{- end }}

{{- end }}
{{- end }}

